version: '3.7'

x-default-opts:
  &default-opts
  logging:
    options:
      max-size: "1m"


services:
  nginx:
    <<: *default-opts
    image: nginx
    #container_name: nginx
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
      - com.example.nginx_proxy=true
    ports:
      - target: 443
        published:  443
        mode: host
        protocol: tcp
      - target: 80
        published:  80
        mode: host
        protocol: tcp
    deploy:
      mode: global  # Either global (exactly one container per swarm node) or replicated (a specified number of containers). The default is replicated
      placement:
        constraints: [node.role == manager]
    networks:
      - nginx
    volumes:
      - ./data/confd:/etc/nginx/conf.d
      - ./data/vhostd:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/htpasswd:/etc/nginx/htpasswd:ro
      - ./nginx.conf:/etc/nginx/nginx.conf

  nginx-gen:
    <<: *default-opts
    image: helder/docker-gen:latest
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen=true
    command:  -notify  "docker-label-sighup com.example.nginx_proxy" -watch -wait 3s:30s  /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    networks:
      - nginx
    volumes:
      - ./data/confd:/etc/nginx/conf.d
      - ./data/vhostd:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/htpasswd:/etc/nginx/htpasswd:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    <<: *default-opts
    image:  jrcs/letsencrypt-nginx-proxy-companion
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    networks:
      - nginx
    volumes:
      - ./data/confd:/etc/nginx/conf.d
      - ./data/vhostd:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs:rw
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro


networks:
  nginx:
    external: true


